### ISSUE TITLE
Version 2.3.2 无法使用

### ISSUE THREAD

**Issue by PythonSmall-Q** [PythonSmall-Q/ClassinMover#19]
### 检查项

- [X] 我已确认了Classin Mover已为最新版，且最新版未修复这个 Bug。
- [x] 我已在 [Issues 页面](https://github.com/PythonSmall-Q/ClassinMover/Issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Classin Mover Version 2.3.2Pro和Free版本输入完检测频率后，无法启动检测。

### 重现步骤

1、输入激活码
2、输入检测频率+回车

### 版本号

Version 2.3.2Pro&Free

**Comment by PythonSmall-Q** [comment]
Okay, I have discovered the problem. I will try to fix the problem with Verification System. Me or another collaborator with fix this in a short time.

**Comment by xiao-k233** [comment]
煞笔开发者倒项目
你的浮木在太空中飞星

**Comment by PythonSmall-Q** [comment]
what? whats going on?

**Comment by PythonSmall-Q** [comment]
If you think this is wrong, then do a DMAC takedown

**Comment by PythonSmall-Q** [comment]
I would really like to see what Github thinks @xiao-k233
